"""
App Configuration — AUTO-GENERATED by pipeline step 05
Generated: 2026-09-08 11:23:36 UTC

DO NOT EDIT MANUALLY. Re-run 05_evaluation/generate_config.py to update.
All metric values are sourced directly from training artifacts.
"""
import os
import json

BASE_DIR   = os.path.dirname(os.path.abspath(__file__))
MODELS_DIR = os.path.join(BASE_DIR, "models")

# ── 1. Screening Thresholds (µg/L) ───────────────────────────────────────────
THRESHOLDS = {
    "Ni": 20.0,   # Research screening threshold (µg/L)
    "Cd":  3.0,   # Research screening threshold (µg/L)
}

# ── 2. Model Configuration (from training artifacts) ─────────────────────────
MODEL_CONFIG = {
    "ni": {
        "name":                    "Nickel (Ni)",
        "symbol":                  "Ni",
        "unit":                    "µg/L",
        "threshold":               THRESHOLDS["Ni"],
        "model_type":              "HuberRegressor",
        "pipeline_description":    "SimpleImputer(median) → StandardScaler → HuberRegressor",
        "model_path":              os.path.join(MODELS_DIR, "ni_model", "FINAL_MODEL_NI.joblib"),
        "conformal_path":          os.path.join(MODELS_DIR, "ni_model", "CONFORMAL_NI.csv"),
        "feature_order":           ['pH_proxy', 'TDS_calc', 'NO3-N_num', 'WELL_DEPTH'],
        "training_n_imputed":      40,
        "training_n_complete_case":39,
        # ── Performance Metrics (5×5 Repeated Nested CV) ──────────────────
        "oof_r2":                  -0.0177,   # Primary: 5×5 Nested CV OOF R²
        "oof_r2_primary":          -0.0177,   # 5×5 Repeated Nested CV Mean
        "oof_r2_secondary":        0.2627, # Single-pass global OOF R²
        "oof_rmse":                1.601,
        "spearman":                0.646,
        # ── Conformal Prediction Interval ─────────────────────────────────
        "conformal_nominal_coverage":   "90%",
        "conformal_observed_coverage":  "90.0% (36/40 samples)",
        "conformal_q_hat_ug_L":         1.714072,
        # ── Scientific Interpretation ──────────────────────────────────────
        "primary_predictor":  "TDS (mg/L)",
        "interpretation":     "TDS is the primary predictive variable in the trained Ni HuberRegressor model.",
        "performance_note":   "Limited quantitative predictive performance (5×5 CV OOF R² = -0.0177)",
        "confidence_level":   "MODERATE SCREENING CONFIDENCE",
    },
    "cd": {
        "name":                    "Cadmium (Cd)",
        "symbol":                  "Cd",
        "unit":                    "µg/L",
        "threshold":               THRESHOLDS["Cd"],
        "model_type":              "LinearRegression",
        "pipeline_description":    "SimpleImputer(median) → StandardScaler → LinearRegression",
        "model_path":              os.path.join(MODELS_DIR, "cd_model", "FINAL_MODEL_CD.joblib"),
        "conformal_path":          os.path.join(MODELS_DIR, "cd_model", "CONFORMAL_CD.csv"),
        "feature_order":           ['pH_proxy', 'TDS_calc', 'NO3-N_num', 'WELL_DEPTH'],
        "training_n_imputed":      40,
        "training_n_complete_case":39,
        # ── Performance Metrics (5×5 Repeated Nested CV) ──────────────────
        "oof_r2":                  0.388,   # Primary: 5×5 Nested CV OOF R²
        "oof_r2_primary":          0.388,
        "oof_r2_secondary":        0.7994,
        "oof_rmse":                0.063,
        "spearman":                0.657,
        # ── Conformal Prediction Interval ─────────────────────────────────
        "conformal_nominal_coverage":  "90%",
        "conformal_observed_coverage": "90.0% (36/40 samples)",
        "conformal_q_hat_ug_L":        0.089842,
        # ── Scientific Interpretation ──────────────────────────────────────
        "primary_predictor":  "NO3-N (mg/L)",
        "interpretation":     "NO3-N is the primary predictive variable in the trained Cd LinearRegression model.",
        "performance_note":   "Stronger quantitative predictive performance (5×5 CV OOF R² = 0.388)",
        "confidence_level":   "HIGHER SCREENING CONFIDENCE",
    },
}

# ── 3. Training Domain Bounds (from domain_bounds.json) ──────────────────────
DOMAIN_BOUNDS_FILE = os.path.join(MODELS_DIR, "domain_bounds.json")

if os.path.exists(DOMAIN_BOUNDS_FILE):
    with open(DOMAIN_BOUNDS_FILE, "r") as f:
        TRAINING_DOMAIN = json.load(f)
else:
    # Fallback: hardcoded from Step 03 output (should not be needed if file exists)
    TRAINING_DOMAIN = {
        "features": {
            "pH_proxy":   {"min": 6.868161,   "max": 7.318283,   "mean": 7.082182,   "std": 0.103764},
            "TDS_calc":   {"min": 38.129,   "max": 537.29,   "mean": 209.7183,   "std": 162.5373},
            "NO3-N_num":  {"min": 0.1,  "max": 12.5,  "mean": 1.445,  "std": 2.6663},
            "WELL_DEPTH": {"min": 9.0, "max": 61.0, "mean": 22.6154, "std": 9.4496},
        },
        "feature_order":            ['pH_proxy', 'TDS_calc', 'NO3-N_num', 'WELL_DEPTH'],
        "mean_vector":              [7.082182, 209.718275, 1.445, 22.615385],
        "inv_covariance":           None,
        "mahalanobis_threshold_95": 3.258414,
        "n_samples":                39,
    }

# ── 4. Validated Ranges (from training domain) ────────────────────────────────
if TRAINING_DOMAIN and "features" in TRAINING_DOMAIN:
    _tf = TRAINING_DOMAIN["features"]
    VALIDATED_RANGES = {
        "pH":         {"min": round(_tf["pH_proxy"]["min"],   4), "max": round(_tf["pH_proxy"]["max"],   4), "unit": "-"},
        "TDS":        {"min": round(_tf["TDS_calc"]["min"],   2), "max": round(_tf["TDS_calc"]["max"],   2), "unit": "mg/L"},
        "NO3-N":      {"min": round(_tf["NO3-N_num"]["min"],  4), "max": round(_tf["NO3-N_num"]["max"],  4), "unit": "mg/L"},
        "Well Depth": {"min": round(_tf["WELL_DEPTH"]["min"], 1), "max": round(_tf["WELL_DEPTH"]["max"],  1), "unit": "m"},
    }
else:
    VALIDATED_RANGES = None

# ── 5. Environmental Reference Ranges (WHO / BIS Standards) ──────────────────
ENVIRONMENTAL_RANGES = {
    "pH":         {"range": "6.5 – 8.5", "unit": "-",    "standard": "WHO / BIS Drinking Water Standard"},
    "TDS":        {"range": "100 – 1000", "unit": "mg/L", "standard": "WHO / BIS Desirable-Permissible Limit"},
    "NO3-N":      {"range": "< 10.0",    "unit": "mg/L", "standard": "WHO / BIS Maximum Permissible Limit"},
    "Well Depth": {"range": "10 – 150",  "unit": "m",    "standard": "Regional Aquifer Context"},
}

# ── 6. Physical Validity Limits (Layer A validation) ─────────────────────────
PHYSICAL_LIMITS = {
    "pH":         {"min": 0.0,   "max": 14.0},
    "TDS":        {"min": 0.0,   "max": 10000.0},
    "NO3-N":      {"min": 0.0,   "max": 500.0},
    "well_depth": {"min": 0.0,   "max": 1000.0},
}

# ── 7. Research Disclaimer ─────────────────────────────────────────────────────
DISCLAIMER_TEXT = (
    "Research prototype — model-based preliminary groundwater screening. "
    "Results do not replace laboratory measurement and should not be "
    "interpreted as definitive regulatory compliance."
)
